# Generated by Django 4.0.3 on 2022-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('re_Password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
