# Generated by Django 4.0.3 on 2022-06-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodApp', '0003_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_file_number_of_the_patient', models.CharField(max_length=100)),
                ('Required_blood_type', models.CharField(max_length=100)),
                ('Number_of_units_required', models.IntegerField()),
                ('Hospital_Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('First_Phone_Number', models.CharField(max_length=14)),
                ('Second_Phone_Number', models.CharField(max_length=14)),
                ('Other_Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='Another_Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
    ]
